version: "3"

services:
  # APコンテナ
  app:
    container_name: laravel
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "50080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # DBコンテナ
  db:
    image: mysql/mysql-server:5.5.62
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "53306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./docker/db/mysql_data:/var/lib/mysql
    env_file:
      - ./docker/db/db-variables.env

  # phpmyadminコンテナ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    ports:
      - "58080:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
